### ISSUE TITLE
'date-time' format does not support non-UTC time zones

### ISSUE THREAD

**Issue by O11o1** [oferei/json-gate#37]
As per https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC , time values of the format

`"2016-10-18T11:11:11.616+05"`

where +05 is represented as the time zone offset from UTC, causes the string to be read as invalid. In contrast

`"2016-10-18T11:11:11.616Z"`

is considered valid (as expected).

**Comment by oferei** [comment]
Hmm, you're right. I read this part of [the documentation](https://tools.ietf.org/html/draft-zyp-json-schema-03#section-5.23):

> date-time  This SHOULD be a date in ISO 8601 format of YYYY-MM-
      DDThh:mm:ssZ in UTC time.  This is the recommended form of date/
      timestamp.

and figured it must end with a Z. But I guess adding the offsets should be easy.

**Comment by oferei** [comment]
fixed.

**Comment by O11o1** [comment]
Thank you!
